### ISSUE TITLE
Include parameters in README

### ISSUE THREAD

**Issue by mvehar** [asyncapi/asyncapi-php-template#4]

**Comment by emilianozublena** [comment]
Hi @mvehar i'd need more details to understand what you're asking for... What do you mean by parameters? atm the only one available is the packageName one, are you referring to those?

Thanks!

**Comment by mvehar** [comment]
Hi @emilianozublena,
first I apologise for missing description. 
We would like to specify custom namespaces for models and controllers. If such parameters will be added, can you list them somewhere.

Thanks!

**Comment by emilianozublena** [comment]
You shouldn't be doing that, customizing your "base" namespace is all you need, all the other underlying folders have their own namespaces. eg: If you specify a packageName parameter as "MyAsyncLibrary" all messages will have the `MyAsyncLibrary/Messages` namespace, all applications will have the `MyAsyncLibrary/Applications` namespace and so on.

There are no controllers nor models in this template.

Does this makes sense to you?
