### ISSUE TITLE
Some anonymous messages are not PSR-4 compliant

### ISSUE THREAD

**Issue by mvehar** [asyncapi/asyncapi-php-template#6]
Adding hook fixes that:

    function toCamelCase(text) {
        return text.replace(/-\w/g, clearAndUpper);
    }
    
    function toPascalCase(text) {
        return text.replace(/(^\w|-\w)/g, clearAndUpper);
    }
    
    function clearAndUpper(text) {
        return text.replace(/-/g, "").toUpperCase();
    }
    
    function clearArrows(text) {
        return text.replace(/[<>]+/g, "");
    }
    
    module.exports = {
        'setFileTemplateName': (generator, hookArguments) => {
            const currentFilename = hookArguments.originalFilename;
    
            return toPascalCase(clearArrows(currentFilename))
        }
    };

**Comment by emilianozublena** [comment]
Hi @mvehar sorry for the delay, i was tooking a few days off.
Can you please fulfill in more details about how/when/where those messages are not complaint? They're all passing the CodeSniffer checks/fixes on generation, so they should be PSR-4 ready.

Also, it would be nice if you follow the [issue template guidelines](https://github.com/asyncapi/asyncapi-php-template/blob/master/ISSUE_TEMPLATE.md) so it's clearer for everyone what is it that you're inquiring.

Thanks for using this template, and feel free to keep sending suggestions, reporting issues and collaborating as well :)

**Comment by mvehar** [comment]
Hi @emilianozublena ,
found the problem when messages under channel/subscribe have $ref and description keys. The generator created additional  Message classes. 
Will close this issue since the problem was wrong yml definition.
